pipelines:
  docker-mono-gide:
    group: stcdev
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:stcdev/docker-mono-gide.git"
        branch: master
        blacklist:
          - "doc/**/*"
          - "**/*.md"
      monoide:
        pipeline: docker-mono-ide
        stage: publish
    stages:
      - verify_version:
          clean_workspace: true
          jobs:
            verify_version:
              resources:
                - docker_builder
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks verify
      - build:
          clean_workspace: true
          jobs:
            docker_image:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: image/imagerc
                    destination:
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks build
      - itest:
          clean_workspace: true
          jobs:
            end_user:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: docker_image
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker_builder
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            docker_image:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: docker_image
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
