format_version: 4
pipelines:
  docker-dotnet-gdojo:
    group: dotnet
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - "doc/**/*"
          - "**/*.md"
      base:
        pipeline: docker-dotnet-dojo
        stage: publish
    secure_variables:
      VAULT_TOKEN: "AES:Dl15kWOR4UuAxeRLVhuqxw==:rp9BrzeZ58v2GqVIOk9KiQCgcmjEiZNn9akIiXvbeq0="
    stages:
      - build:
          clean_workspace: true
          jobs:
            docker_image:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: image/imagerc
                    destination:
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks build
      - itest:
          clean_workspace: true
          jobs:
            end_user:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: docker_image
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker_builder
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            docker_image:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: build
                    job: docker_image
                    is_file: yes
                    source: imagerc
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
