# {{BASE_IMAGE_VERSION}} must be replaced with existing git tag.
# I added {{ }} so that docker build fails if it is not replaced.
FROM {{BASE_IMAGE_NAME}}:{{BASE_IMAGE_VERSION}}

# Install visual studio code
ENV VSCODE_VERSION="1.27.2"
RUN apt-get update &&\
  DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install \
  libgtk-3-0 libasound2 libatk1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
  libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
  libxtst6 libsecret-1-0 libxss1 libnotify4 libnss3 libxkbfile1 libgconf-2-4 libxtst6 &&\
  apt-get clean && rm -rf /tmp/* /var/tmp/* && rm -rf /var/lib/apt/lists/* &&\
  wget -O code.deb https://vscode-update.azurewebsites.net/${VSCODE_VERSION}/linux-deb-x64/stable &&\
  dpkg -i code.deb && rm code.deb

# Install visual studio extensions
# * http://gogs.ai-traders.com:3333/stcdev/vsix-csharpextensions builds vsix
# package of https://github.com/jchannon/csharpextensions
ENV OMNISHARP_VSCODE_VERSION="1.16.1" \
  IONIDE_VSCODE_FSHARP_VERSION="3.27.0" \
  IONIDE_VSCODE_FAKE_VERSION="1.2.3" \
  IONIDE_VSCODE_PACKET_VERSION="1.12.0" \
  VSCODE_DOCOMMENT_VERSION="0.1.0" \
  CSHARPEXTENSIONS_VERSION="1.3.0" \
  VSCODE_DOCKER_VERSION="0.6.1"
RUN wget -O csharp.vsix https://github.com/OmniSharp/omnisharp-vscode/releases/download/v${OMNISHARP_VSCODE_VERSION}/csharp-${OMNISHARP_VSCODE_VERSION}.vsix &&\
  sudo -E -H -u dojo /bin/bash -c "code --install-extension csharp.vsix" &&\
  rm csharp.vsix &&\
  wget https://github.com/ionide/ionide-vscode-fsharp/releases/download/${IONIDE_VSCODE_FSHARP_VERSION}/Ionide-fsharp-${IONIDE_VSCODE_FSHARP_VERSION}.vsix &&\
  sudo -E -H -u dojo /bin/bash -c "code --install-extension Ionide-fsharp-${IONIDE_VSCODE_FSHARP_VERSION}.vsix" &&\
  rm Ionide-fsharp-${IONIDE_VSCODE_FSHARP_VERSION}.vsix &&\
  wget https://github.com/ionide/ionide-vscode-fake/releases/download/${IONIDE_VSCODE_FAKE_VERSION}/Ionide-FAKE-${IONIDE_VSCODE_FAKE_VERSION}.vsix &&\
  sudo -E -H -u dojo /bin/bash -c "code --install-extension Ionide-FAKE-${IONIDE_VSCODE_FAKE_VERSION}.vsix" &&\
  rm Ionide-FAKE-${IONIDE_VSCODE_FAKE_VERSION}.vsix &&\
  wget https://github.com/ionide/ionide-vscode-paket/releases/download/${IONIDE_VSCODE_PACKET_VERSION}/Ionide-Paket-${IONIDE_VSCODE_PACKET_VERSION}.vsix &&\
  sudo -E -H -u dojo /bin/bash -c "code --install-extension Ionide-Paket-${IONIDE_VSCODE_PACKET_VERSION}.vsix" &&\
  rm Ionide-Paket-${IONIDE_VSCODE_PACKET_VERSION}.vsix &&\
  wget https://github.com/k--kato/vscode-docomment/releases/download/v${VSCODE_DOCOMMENT_VERSION}/docomment-${VSCODE_DOCOMMENT_VERSION}.vsix &&\
  sudo -E -H -u dojo /bin/bash -c "code --install-extension docomment-${VSCODE_DOCOMMENT_VERSION}.vsix" &&\
  rm docomment-${VSCODE_DOCOMMENT_VERSION}.vsix &&\
  wget -O vscode-docker.vsix https://github.com/Microsoft/vscode-docker/releases/download/v${VSCODE_DOCKER_VERSION}/vscode-docker-${VSCODE_DOCKER_VERSION}.vsix &&\
  sudo -E -H -u dojo /bin/bash -c "code --install-extension vscode-docker.vsix" &&\
  rm vscode-docker.vsix
# This is an archived project with no binaries published, we have to
# either get them from a local cache or stop using this project.
RUN wget -O csharpextensions.vsix http://http.archive.ai-traders.com/csharpextensions/${CSHARPEXTENSIONS_VERSION}/csharpextensions-${CSHARPEXTENSIONS_VERSION}.vsix &&\
  sudo -E -H -u dojo /bin/bash -c "code --install-extension csharpextensions.vsix" &&\
  rm csharpextensions.vsix

# Install vscode settings
COPY vscode_settings.json /home/dojo/.config/Code/User/settings.json
RUN chown dojo:dojo /home/dojo/.config/Code/User/settings.json

# For Bash
COPY bashrc_default /home/dojo/.bashrc
RUN chown dojo:dojo -R /home/dojo

COPY etc_dojo.d/scripts/* /etc/dojo.d/scripts/

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["/bin/bash"]
