# {{BASE_IMAGE_VERSION}} must be replaced with existing git tag.
# I added {{ }} so that docker build fails if it is not replaced.
FROM docker-registry.ai-traders.com/mono-ide:{{BASE_IMAGE_VERSION}}

# next is 7.5.0.1222-0xamarin1+debian8b1
ENV MONODEVELOP_VERSION 7.4.0.1033-0xamarin57+debian8b1
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF &&\
  echo "deb http://download.mono-project.com/repo/debian vs-jessie main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list &&\
  apt-get update &&\
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends\
  monodevelop=${MONODEVELOP_VERSION} monodevelop-nunit=${MONODEVELOP_VERSION} monodevelop-versioncontrol=${MONODEVELOP_VERSION} mono-xsp4 xdot &&\
  apt-get -y autoremove && apt-get -y autoclean && apt-get -y clean &&\
  rm -rf /tmp/* /var/tmp/* && rm -rf /var/lib/apt/lists/*

COPY monodevelop-config/ /home/ide/.config/MonoDevelop/7.0
COPY monodevelop-local-config/ /home/ide/.config/MonoDevelop/7.0

# Install visual studio code
ENV VSCODE_VERSION="1.23.0"
RUN apt-get update &&\
  DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install \
  libasound2 libatk1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
  libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
  libxtst6 libsecret-1-0 libxss1 libnotify4 libnss3 libxkbfile1 libgconf-2-4 libxtst6 &&\
  apt-get clean && rm -rf /tmp/* /var/tmp/* && rm -rf /var/lib/apt/lists/* &&\
  wget -O code.deb https://vscode-update.azurewebsites.net/${VSCODE_VERSION}/linux-deb-x64/stable &&\
  dpkg -i code.deb && rm code.deb

# Install visual studio extensions
# * http://gogs.ai-traders.com:3333/stcdev/vsix-csharpextensions builds vsix
# package of https://github.com/jchannon/csharpextensions
ENV OMNISHARP_VSCODE_VERSION="1.15.0-beta6" \
  IONIDE_VSCODE_FSHARP_VERSION="3.19.4" \
  IONIDE_VSCODE_FAKE_VERSION="1.2.3" \
  IONIDE_VSCODE_PACKET_VERSION="1.9.1" \
  VSCODE_DOCOMMENT_VERSION="0.1.0" \
  CSHARPEXTENSIONS_VERSION="1.3.0" \
  VSCODE_DOCKER_VERSION="0.0.16"
RUN wget https://github.com/OmniSharp/omnisharp-vscode/releases/download/v${OMNISHARP_VSCODE_VERSION}/csharp-${OMNISHARP_VSCODE_VERSION}.vsix  &&\
  sudo -E -H -u ide /bin/bash -c "code --install-extension csharp-${OMNISHARP_VSCODE_VERSION}.vsix" &&\
  rm csharp-${OMNISHARP_VSCODE_VERSION}.vsix &&\
  wget https://github.com/ionide/ionide-vscode-fsharp/releases/download/${IONIDE_VSCODE_FSHARP_VERSION}/Ionide-fsharp-${IONIDE_VSCODE_FSHARP_VERSION}.vsix &&\
  sudo -E -H -u ide /bin/bash -c "code --install-extension Ionide-fsharp-${IONIDE_VSCODE_FSHARP_VERSION}.vsix" &&\
  rm Ionide-fsharp-${IONIDE_VSCODE_FSHARP_VERSION}.vsix &&\
  wget https://github.com/ionide/ionide-vscode-fake/releases/download/${IONIDE_VSCODE_FAKE_VERSION}/Ionide-FAKE-${IONIDE_VSCODE_FAKE_VERSION}.vsix &&\
  sudo -E -H -u ide /bin/bash -c "code --install-extension Ionide-FAKE-${IONIDE_VSCODE_FAKE_VERSION}.vsix" &&\
  rm Ionide-FAKE-${IONIDE_VSCODE_FAKE_VERSION}.vsix &&\
  wget https://github.com/ionide/ionide-vscode-paket/releases/download/${IONIDE_VSCODE_PACKET_VERSION}/Ionide-Paket-${IONIDE_VSCODE_PACKET_VERSION}.vsix &&\
  sudo -E -H -u ide /bin/bash -c "code --install-extension Ionide-Paket-${IONIDE_VSCODE_PACKET_VERSION}.vsix" &&\
  rm Ionide-Paket-${IONIDE_VSCODE_PACKET_VERSION}.vsix &&\
  wget https://github.com/k--kato/vscode-docomment/releases/download/v${VSCODE_DOCOMMENT_VERSION}/docomment-${VSCODE_DOCOMMENT_VERSION}.vsix &&\
  sudo -E -H -u ide /bin/bash -c "code --install-extension docomment-${VSCODE_DOCOMMENT_VERSION}.vsix" &&\
  rm docomment-${VSCODE_DOCOMMENT_VERSION}.vsix &&\
  wget -O csharpextensions.vsix http://http.archive.ai-traders.com/csharpextensions/${CSHARPEXTENSIONS_VERSION}/csharpextensions-${CSHARPEXTENSIONS_VERSION}.vsix &&\
  sudo -E -H -u ide /bin/bash -c "code --install-extension csharpextensions.vsix" &&\
  rm csharpextensions.vsix &&\
  wget -O vscode-docker.vsix http://http.archive.ai-traders.com/vscode-docker/${VSCODE_DOCKER_VERSION}/vscode-docker-${VSCODE_DOCKER_VERSION}.vsix &&\
  sudo -E -H -u ide /bin/bash -c "code --install-extension vscode-docker.vsix" &&\
  rm vscode-docker.vsix

# Install vscode settings
COPY vscode_settings.json /home/ide/.config/Code/User/settings.json
RUN chown ide:ide /home/ide/.config/Code/User/settings.json

# For Bash
COPY bashrc_default /home/ide/.bashrc
RUN chown ide:ide -R /home/ide

COPY etc_ide.d/scripts/* /etc/ide.d/scripts/
COPY etc_ide.d/variables/*.sh /etc/ide.d/variables

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["/bin/bash"]
